#!/usr/bin/env sh
#
# Description
#   Get temperature and precipitation of your local city
#
# Dependencies
#   tuxi
#
# BeyondMagic © 2021

_temp() {

  utilites_fg="#666666"
  fg="#FFFFFF"

   first_icon="#9E4542"
  second_icon="#C88658"
   third_icon="#A3AB60"

  bg="#14181B"

  tp_icon="  "
  pp_icon="  "
  hd_icon="  "

  while :; do

        tuxi_result=$(tuxi -trq "tuxi_weather weather now")
    formated_result=$(echo "$tuxi_result" | grep -hoE '[0-9]{2}' | sed \
      -e "2d;5d" \
      -e "1 s/$/%{F$utilites_fg}ºC /;1 s/^/%{F$first_icon B$bg T3}$tp_icon%{T1 F$fg}/" \
      -e "3 s/$/%{F$utilites_fg}%% /;3 s/^/%{F$second_icon B$bg T3}$pp_icon%{T1 F$fg}/" \
      -e "4 s/$/%{F$utilites_fg}%% /;4 s/^/%{F$third_icon B$bg T3}$hd_icon%{T1 F$fg}/" \
      | tr '\n' ' ')
    
    echo 'W' "$formated_result"

    sleep 300

  done
}

_temp
