#!/usr/bin/env sh
#
# Simple Fetch tool
#
# Dependencies
#   
#
# BeyondMagic © 2021


     columns=$(tput cols)
 icons_first="\e[30m  \e[31m  \e[32m  \e[33m  \e[34m  \e[35m  \e[36m  \e[37m"
icons_second="\e[90m  \e[91m  \e[92m  \e[93m  \e[94m  \e[95m  \e[96m  \e[97m"

source "`ueberzug library`"

# If there are not enough icons
#   Minimum: 16
[ "${#icons_second}" -le 8 ] || [ "${#icons_first}" -le 8 ] && {

  echo "Please, add more icons, currently there are $((${#icons_first} - 1)) & $((${#icons_second} - 1)). There should be at least 16 counting both."
  exit 1

}



# Function
#   Center input text based on the terminal's size
center() {

  quantify="$2"
  spaces=""

  for (( i = 0; i < $((columns/2 - quantify)); i++ )); do

    spaces="$spaces "

  done

  echo -e "$spaces$1"

}

# Print pallete

center "$icons_first" "11"
center "$icons_second" "11"


#ueberzug layer --parser bash 0< <(
#  declare -Ap cmd=(
#   [action]=add [identifier]="${PREVIEW_ID}" \
    [x]="${X}" [y]="${Y}" \
#    [width]="${COLUMNS}" [height]="${LINES}" \
#        [scaler]=fit_contain [scaling_position_x]=0.5 [scaling_position_y]=0.5 \
#        [path]="/tmp/tmp.fzfwpp_img")
        # force überzug to stay open
#        sleep 1h
#    )
