#!/usr/bin/env sh
#
# Description
#   Simple Fetch tool for Artix... can be adapted.
#
# BeyondMagic © 2021


     columns=$(tput cols)
 icons_first="\033[30m   \033[31m   \033[32m   \033[33m   \033[34m   \033[35m   \033[36m   \033[37m "
icons_second="\033[90m   \033[91m   \033[92m   \033[93m   \033[94m   \033[95m   \033[96m   \033[97m "


unset p id

# Function
#   Center input text based on the terminal's size
center() {

  quantify="$2"
  spaces=""

  i=0 ; while [ "$i" -lt $((columns/2 - quantify)) ]; do

    spaces="$spaces "
    i=$((i+1))

  done 

  printf '%b' "$spaces$1\n"

}


# If there are not enough icons
#   Minimum: 16
[ "${#icons_second}" -le 8 ] || [ "${#icons_first}" -le 8 ] && {

  echo "Please, add more icons, currently there are $((${#icons_first} - 1)) & $((${#icons_second} - 1)). There should be at least 16 counting both."
  exit 1

}


# Method
#   Format line for logo
format_line() {

  # Information for every line
  [ $i = 5 ] && line="$line \033[31m \033[39m  $(id | sed -r 's/(uid=1000\()|\) gid.*//g') : flora"
  [ $i = 6 ] && line="$line \033[32m \033[39m  $(cat /etc/*release | head -n 1 | sed -r 's/(NAME=")|("$)//g')"
  [ $i = 7 ] && line="$line \033[33m \033[39m  $(uname -r)"
  [ $i = 8 ] && line="$line \033[34m \033[39m  $(uptime -p | sed 's/^up //')"
  [ $i = 9 ] && line="$line \033[35m \033[39m  $(echo $SHELL)"
  [ $i = 10 ] && line="$line \033[36m \033[39m  $(pacman -Q | wc -l) packages"

  printf '%b' "$line\n"

  #printf '%b' "$i $line\n"

}


# Function
#   Artix logo
logo() {

  a_logo=$(echo "
                AR             
               AAAR            
              AAAAAR           
             AAAAAAAR          
            AAAAAAAAAR         
                AAAAAAR        
          AAA      AAAAR       
         AAAAAAA       AR      
        AAAAAAAAAAA            
       AAAAAAAAAAAAAAA         
      AAAAAAAAAA/        AAR   
     AAAAAAA/         :AAAAAR  
    AAA/                  AAAA 
  " | sed -re "s/[^ ]/\\\033[22m:\\\033[39m/g")

  # Loop through every line to format
  i=1; echo "$a_logo" | while IFS= read line; do

    format_line "$i" "$line"

  i=$((i+1)); done 

}


# Logo and information
logo

# Print pallete

center "$icons_first" "14"
center "$icons_second" "14"

printf "\n"
