#!/usr/bin/env sh
#
# DESCRIPTION:
#   Add a new quote to a .json file.
#
# DEPENDENCIES:
#   sed (gnu)
#
# WARNING:
#   this script will overwrite the quote file.
#
# NOTE:
# -------quotes.json--------
#[
#  [
#    "Your Majesty, we Catholic clergy have done our best to destroy the Church for the last eighteen hundred years. We have not succeeded, and neither will you.",
#    "Massimo Faggioli"
#  ]
#]
# ---------------------------
#
# Examples:
#   ./this_executable "This generation fights sex trafficking more than anyone ever has and more than anyone ever has this generation consumes pornography."
#   ./this_executable "É a batalha pela mente, guerra psicológica. Levando a loucura, tortura neurológica." "Zamba" "A Arte da Guerra"
#   quotes_path="$HOME/quotes.json" $HOME/scripts/thix_executable "That's why we sing for these kids who don't have a thing, except for a dream and a fucking rap magazine." "Eminem"
#
#
# Arguments:
#   $1 : quote
#   $2 : author (optional)
#   $3 : source (optional)
#
# Set:
#   quotes_path = path of the quotes.json file
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2022-

[ "$quotes_path" ] || quotes_path="$HOME/Library/quotes.json"

quote=$(printf "$1" | awk 1 ORS='\\\\n' | head -c -2 )

# See if file exists

   [ ! -e "$quotes_path" ] && {

  echo -e "No file encountered, current path being passed is:" \
  "\n\$quotes_path : $quotes_path\n" \
  "\nEdit this executable file to change the path or execute it with " \
  "'quotes_path' variable, for example:\n  " \
  "quotes_path=\"/path_to_quotes/quotes_file.json\"$basename $0" \
  " \"Life is cool.\" \"Me\""
  exit 1

}

# Four?
  [ ! "$4" = "" ] && {

  echo "Please, only three arguments..."
  exit 1
  
# Three arguments passed
} || [ ! "$3" = "" ] && {

  echo "Three arguments passed:
\033[1;31m\$1 \033[90m・ \033[91m$1
\033[32m\$2 \033[90m・ \033[92m$2
\033[33m\$3 \033[90m・ \033[93m$3\033[0m"

  sed \
    -e '1 a ¨¨[' \
    -e "1 a ¨¨¨¨\"$quote\"," \
    -e "1 a ¨¨¨¨\"$2\"," \
    -e "1 a ¨¨¨¨\"$3\"" \
    -e '1 a ¨¨],' "$quotes_path" | \
    sed '2,6s/¨/ /g' > "$quotes_path.tmp" \
    && mv "$quotes_path.tmp" "$quotes_path" || \
    { echo "Failed to save quote, please review the error" \
      "message and be sure that you're using GNU sed."; exit 1; }
  echo "Saved new quote."
  exit 0

# Two arguments passed
} || [ ! "$2" = "" ] && {

    echo "Two arguments passed:
\033[1;31m\$1 \033[90m・ \033[91m$1
\033[32m\$2 \033[90m・ \033[92m$2\033[0m"

  sed \
    -e '1 a ¨¨[' \
    -e "1 a ¨¨¨¨\"$quote\"," \
    -e "1 a ¨¨¨¨\"$2\"" \
    -e '1 a ¨¨],' "$quotes_path" | \
    sed '2,5s/¨/ /g' > "$quotes_path.tmp" \
    && mv "$quotes_path.tmp" "$quotes_path" || \
    { echo "Failed to save quote, please review the error" \
      "message and be sure that you're using GNU sed."; exit 1; }
  echo "Saved new quote."
  exit 0

# One argument passed
} || [ ! "$1" = "" ] && {

  echo "One argument passed:
\033[1;31m\$1 \033[90m・ \033[91m$1\033[0m"

  sed \
    -e '1 a ¨¨[' \
    -e "1 a ¨¨¨¨\"$quote\"" \
    -e '1 a ¨¨],' "$quotes_path" | \
    sed '2,4s/¨/ /g' > "$quotes_path.tmp" \
    && mv "$quotes_path.tmp" "$quotes_path" || \
    { echo "Failed to save quote, please review the error" \
      "message and be sure that you're using GNU sed."; exit 1; }
  echo "Saved new quote."
  exit 0

# No arguments passed, exit error
} || {
  
  echo "Please, pass at least one arguments (quote)."
  exit o1

}
