#!/usr/bin/env sh
#
# Imagemagick.
#
# João F. BeyondMagic © <koetemagie@gmail.com> 

# 1. Set variables
bg_path="$(tail -n1 "$XWALLPAPER_HISTORY")"
bg_name="$(basename "$bg_path")"
bg_temp="/tmp/tmp_$bg_name"

# 2. Aliases to apply the same settings for Xorg.
alias xwall='xwallpaper --stretch'

# 2. Remove the penultimate wallpaper in case of new.
#if [ "$bg_temp" = "$()" ]; then

# 3. Apply ...
case "$1" in

  # 1.
  blur )

    # I. See if blur was already applied.
    if [ ! -f "$bg_temp" ]; then

      # A. Apply blur.
      convert -scale 10% -blur 0x2 -resize 1000% "$bg_path" "$bg_temp"

      # B. Create symbolyc link for EWW.
      ln -sf "$bg_temp" "$HOME/.cache/xcurrent_wallpaper"

    fi

    # II. Apply wallpaper.
    xwall "$bg_temp"

  ;;

  # 2.
  unblur )

    # I. Apply the current wallpaper.
    xwall "$bg_path"

  ;;

  * )

    # I. Rest.
    echo "Please specify an option to use. Either 'blur' or 'unblur'. "

  ;;

esac
