#!/usr/bin/env sh

text="$1"

max_length() {

  echo "$text" | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | tail -n1 | wc -m

}

length=$(max_length)

# Function.
#   Center input text based on the terminal's size.
center() {

  amount="$(( $(echo "$1" | wc -m) - 1 ))"

  # Spaces on the start of the line.
  spaces_to_add="$(( ($length - $amount) / 2 ))"

  # Print lines on stdout.
  echo "$1" | sed -e "s/^/$(printf %${spaces_to_add}s)/"

}

echo "$text" | while IFS="" read -r line || [ -n "$line" ]; do

  center "$line"

done
