#!/usr/bin/env sh

# 1. Set main variables.
icons="$HOME/.local/share/icons"

# 2. Retrieve command to execute.
command="$(echo "
IMG:$icons/flarity.svg	Terminal Emulator	flarity

IMG:$icons/internet.svg	Web Browser
	IMG:$icons/firefox.svg	Firefox Nightly	zsh -c 'haha'
	IMG:$icons/brave.svg	Brave Nightly	zsh -c 'lol'

IMG:$icons/neovim.png	Text Editor	flarity -e nvim
IMG:$icons/applications.svg	Applications
	IMG:$icons/gimp.svg	Inkscape	inkscape
	IMG:$icons/gimp.png	Telegram	telegram-desktop
	IMG:$icons/gimp.png	Shazam	songrec
	IMG:$icons/gimp.png	Zathura	zathura
	IMG:$icons/gimp.png	Tenacity	tenacity
	IMG:$icons/gimp.png	Gimp	gimp-2.10
	IMG:$icons/gimp.png	Monero Wallet	monero-wallet-gui
	IMG:$icons/gimp.png	Terra Station	station-electron
	IMG:$icons/gimp.png	Deezer	deemix-gui
	IMG:$icons/gimp.png	MPV	mpv --player-operation-mode=pseudo-gui
	IMG:$icons/gimp.png	VLC	vlc
	IMG:$icons/gimp.png	qBitTorrent	qbittorrent
	IMG:$icons/gimp.png	xSnow	xsnow
IMG:$icons/web.png	Screen
	IMG:$icons/gimp.png	Set Size Screenshot	screen
	IMG:$icons/gimp.png	Full Screenshot	fullscreen
	
	IMG:$icons/gimp.png	Set Size in GIF	screen
	IMG:$icons/gimp.png	Full Display GIF	fullscreen
	IMG:$icons/gimp.png	Set Size MKV	screen
	IMG:$icons/gimp.png	Full Display MKV	fullscreen

IMG:$icons/web.png	Places
IMG:$icons/web.png	Bookmarks
IMG:$icons/web.png	Preferences
IMG:$icons/web.png	Keybinds	flarity -e "nvim" ".config/xbindkeys/xbindkeysrc"

IMG:$icons/web.png	Lock Screen	lock
IMG:$icons/web.png	System
	IMG:$icons/gimp.png	Status
		
		    $(id -G -n | sed "s/ /@/") | $(date +'%H:%M, %a%b %d')   
		
		  OS       $(cat /etc/os-release | grep -m 1 -oP '((?<=NAME=").*(?= Linux"))') - GNU/Linux - x86_64
		  KERNEL   Linux $(uname -r)
		  UPTIME   $(uptime -p | sed 's/^up //')
		  SHELL    $(echo "$SHELL" | sed 's_/usr/bin/__')
		  PACKAGES $(pacman -Q | wc -l) packages
		  INIT     $(ls -l /sbin/init | grep -oP '((?<=-> ).*(?=-init))')
		  MEMORY   $(free -m | awk '{print $3}' | head -n2 | tail -n1)MiB
	IMG:$icons/gimp.png	Shutdown	doas halt
	IMG:$icons/gimp.png	Reboot	doas -- shutdown -r now
	IMG:$icons/gimp.png	Sleep	doas -- zzz
	IMG:$icons/gimp.png	Log-out	exec unlovemii
	IMG:$icons/gimp.png	Restart Window Manager	dwm-msg run_command quit 1

IMG:$icons/web.png	Wallpaper
	IMG:$icons/web.png	New Random Wallpaper	zsh -c '. ~/.config/zsh/aliasesrc; random_wallpaper'
	IMG:$icons/gimp.png	See Wallpapers	zsh -c '. ~/.config/zsh/aliasesrc; set_wallpaper'
" \
| sed -re '1d;$d' | xmenu)"

# II. Execute command in fly.
eval "$command"
