#!/usr/bin/env sh
#
# Description
#   Load MPD info every time MPD updates
# 
# Dependencies:
#		91menu
#
# BeyondMagic  GPL3 LICENSE  2021

option=$(echo \
	"lemonbar: Restart." \
	"\nlemonbar-modules: Restart modules of bars." \
	"\nrandom wallpaper: Random wallpaper." \
	"\nprevious wallpaper: Select previous wallpaper." \
	"\ndelete wallpaper: Delete current wallpaper." \
	| 91menu | sed -r 's/:.+//')

#	"st: Open Simple Terminal." \
#	"st-float: Open Simple Terminal in floating mode." \
#	"\nfox: Open browser." \
#	"\ntelegram: Open Telegram Desktop." \

origin="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"

case "$option" in

#	st)

#		nohup st >/dev/null 2>&1 &

#	;;

#	st-float)

#		nohup $HOME/Git/Projects/creamberry/terminal/st_float >/dev/null 2>&1 &

#	;;

#	fox)

#		xdo activate -N Nightly	|| nohup firefox-nightly >/dev/null 2>&1 &

#	;;

#	telegram)

#		xdo activate -N telegram-desktop || nohup telegram-desktop >/dev/null 2>&1 &

#	;;

  lemonbar)

    ~/Git/Projects/creamberry/bars/modules clean
    ~/Git/Projects/creamberry/bars/lemonbars clean
    ~/Git/Projects/creamberry/bars/lemonbars
    ~/Git/Projects/creamberry/bars/modules

  ;;

  lemonbar-modules)

    ~/Git/Projects/creamberry/bars/modules clean
    ~/Git/Projects/creamberry/bars/modules

  ;;

	'random wallpaper')

		zsh -c '. ~/Base/aliasesrc; random_wallpaper'

	;;

	'previous wallpaper')	

		zsh -c '. ~/Base/aliasesrc; previous_wallpaper'

	;;

	'delete wallpaper')	

		zsh -c '. ~/Base/aliasesrc; delete_wallpaper'

	;;

esac
