#!/usr/bin/env sh
#
# Description
#   Simple Fetch tool for Artix... can be adapted.
#
# BeyondMagic 🄯 2021

unset p id columns icons_first icons_second

     columns=$(tput cols)
 icons_first="\033[30m   \033[31m   \033[32m   \033[33m   \033[34m   \033[35m   \033[36m   \033[37m  "
icons_second="\033[90m   \033[91m   \033[92m   \033[93m   \033[94m   \033[95m   \033[96m   \033[97m  "


# If there are not enough icons
#   Minimum: 16
[ "${#icons_second}" -le 8 ] || [ "${#icons_first}" -le 8 ] && {

  echo "Please, add more icons, currently there are $((${#icons_first} - 1)) & $((${#icons_second} - 1)). There should be at least 16 counting both."
  exit 1

}


# Function
#   Center input text based on the terminal's size
center() {

  quantify="$2"
  spaces=""

  j=0 ; while [ "$j" -lt $((columns/2 - quantify)) ]; do

    spaces="$spaces "
    j=$((j+1))

  done

  printf '%b' "$spaces$1\n"

}

# Method
#   Format line for logo
format_line() {

#  [ $i = 3 ] && line="$line \033[32m \033[39m  $(cat /etc/*release | head -n 1 | sed -r 's/(NAME=")|("$)//g')"

  # Information for every line
  [ $i = 2 ] && line="$line \033[31m  \033[39m  $(id | sed -r 's/(uid=1000\()|\) gid.*//g') : arcoiris"
  [ $i = 3 ] && line="$line \033[33m  \033[39m  $(uname -r)"
  [ $i = 4 ] && line="$line \033[34m  \033[39m  $(uptime -p | sed 's/^up //')"
  [ $i = 5 ] && line="$line \033[35m  \033[39m  $(echo $SHELL)"
  [ $i = 6 ] && line="$line \033[36m  \033[39m  $(pacman -Q | wc -l) packages"

  center "$line" "23"

}


# Function to show everything with the logo
logo() {

  # Ascii art by Dawid Potocki @dawidpotocki on Gitlab
  a_logo=$(cat <<EOF
        / ﹨         
       /   ﹨       
      / '., ﹨      
     /     ',﹨     
    /      ,\` ﹨    
   /   ,.'\`.   ﹨   
  / ,'\`     \`'. ﹨ 
EOF
)

  # Just add the colour in every line of the art
  a_logo=$(echo "$a_logo" | sed -re "s/^/\\\033[25m/")

  # Loop through every line to format
  i=1; echo "$a_logo" | while IFS= read line; do

    # What do you think this does?
    format_line

  i=$((i+1)); done 

}



# Clear terminal
clear

# Logo and information
logo

printf "\n"

# Print pallete
center "$icons_first" 14
center "$icons_second" 14

printf "\n"
