#!/usr/bin/env sh
#
# DESCRIPTION:
#   Load a notification for the current song with
#   a cover.
#
# DEPENDENCIES:
#   notify-call
#   mpd
#     mpc
#   imagemagick
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2022-

# 1. Clean off the folling variables.
unset music_path artist title file a b c size image

# 2. Set them.
{

      cover_empty="$HOME/.local/share/icons/no_cover.png"
     cover_square='/tmp/cover_square.jpg'
     cover_circle='/tmp/cover_circle.png'
       cover_blur='/tmp/cover_blur.jpg'
  cover_temporary='/tmp/cover_tmp.jpg'

  music_path="$HOME/Library/Music/Songs"

  artist="$(mpc -f "%artist%" | head -n 1)"
   title="$(mpc -f "%title%"  | head -n 1)"
    file="$(mpc -f "%file%"   | head -n 1)"

  # A. Capitalize special varibles.
  artist="$(echo "$artist" | tr '[:lower:]' '[:upper:]')"

  # B. Update special variables.
  #eww update current_song_artist="$artist"
  #eww update current_song_name="$title"

}

# 3. Extract image from song file.
ffmpeg -loglevel quiet -i "$music_path/$file" "$cover_temporary"

# 4. If it doesn't find an image to extract from song file.
if [ -f "$cover_temporary" ]; then

  # A. Get image information.
  c="circle 112,112,112,225"

  # B. Create cropped circle from the image file.
  convert "$cover_temporary" \
    -scale '225x225' \
    \( +clone \
      -fill Black -colorize 100 \
      -fill White -draw "$c" \
    \) \
    -alpha off -compose CopyOpacity -composite -fill None -draw "$c" \
    "$cover_circle"

  # C. Notify the song with image.
  notify-call \
    --hint string:image-path:"$cover_circle" \
    "$artist" \
    "$title"

  # D. Create blurred image.
  convert -scale 1% -blur 0x1 -fill black -colorize 55% "$cover_temporary" "$cover_blur"

  # E. Copy original image.
  mv -f "$cover_temporary" "$cover_square"

  # F. Update MPD image.
  #eww update mpd_image_path="$cover_square"

  # G. Add lyrics to database.
  mpd-lyrics-song

else

  # A. Notify the song without any image.
  notify-call "$artist" "$title"

  # B. Remove all image files.
  rm -f "$cover_circle" "$cover_blur"

  # C. Update image file to not update.
  #eww update mpd_image_path="$cover_empty"

fi
