#!/usr/bin/env sh
#
# DESCRIPTION:
#   Save the lyrics of current song to a folder.
#
# DEPENDENCIES:
#   mpd
#   mpc
#   iris
#
# João F. © BeyondMagic 2022 <koetemagie@gmail.com>

export LANG=en_US

# 0. Path of iris.
iris_bin="$HOME/Git/Projects/iris-cli/iris/bin/iris"

# #. 
clean () {

  sed -r 's/\/|\.|-|\;|\&|\?|\!/_/g'

}

{
  # 1. Get current Artist and Song Name with mpc.
  name_artist="$(mpc -f "[%artist%]" | head -n1 | clean)"
  name_song="$(mpc -f "[%title%]" | head -n1 | clean)"
  name_album="$(mpc -f "[%album%]" | head -n1 | clean)"

  # 2. Set paths for folder and lyrics to save for later use.
  folder_lyrics="$HOME/Library/Music/Lyrics/$name_artist/$name_album"
  file_lyrics="$folder_lyrics/$name_song.txt"
}

# 3. If file exist, just exit.
[ -f "$file_lyrics" ] && cat "$file_lyrics" && exit 0

# 4. Create folder to add a new file.
mkdir -p "$folder_lyrics"

# 5. Get file
lyrics="$("$iris_bin" "$name_artist $name_song lyrics" | awk '$1 !~ /Information/ { $1=""; print substr($0,2) }')"

# 6. If lyrics exist at all.
[ "$lyrics" ] && {

  # A. Save them.
  echo "$lyrics" > "$file_lyrics"

} || {

  # A. Save no lyrics.
  echo '' > "$file_lyrics"

}

cat "$file_lyrics"
