#!/usr/bin/env sh
#
# DESCRIPTION:
#   Save the lyrics of current song to a folder.
#
# DEPENDENCIES:
#   mpd
#   mpc
#   iris
#
# João F. © BeyondMagic 2022 <koetemagie@gmail.com>

# #. 
clean () {

  head -n 1 | sed -r 's/\/|\.|-|\;|\&|\?|\!/_/g'

}

{
  # 1. Get current Artist and Song Name with mpc.
  name_artist="$(mpc -f "[%artist%]" | clean)"
  name_song="$(mpc   -f "[%title%]"  | clean)"
  name_album="$(mpc  -f "[%album%]"  | clean)"

  # 2. Set paths for folder and lyrics to save for later use.
  folder_lyrics="$HOME/Library/Music/Lyrics/$name_artist/$name_album"
  file_lyrics="$folder_lyrics/$name_song.txt"
}

# 3. If file exist, test first argument.
if [ -f "$file_lyrics" ]; then

  # A. Let the user edit the file.
  if [ "$1" = 'edit' ] || [ "$1" = 'e' ]; then

    # I. Use environment variable of text-editor.
    $EDITOR "$file_lyrics"

  else

    # II. Pipe the text into stdout instead if nothing else is asked.
    cat "$file_lyrics"

  fi

  exit 0

fi

# 4. Create folder to add a new file.
mkdir -p "$folder_lyrics"

# 5. Get file
lyrics="$(LANG=en_US iris "$name_artist $name_song lyrics" | awk '$1 == "GoogleLyrics" { $1=""; print substr($0,2) }')"

# 6. If lyrics exist at all.
if [ "$lyrics" ]; then

  # A. Save them.
  echo "$lyrics" > "$file_lyrics"

else

  # A. Save no lyrics.
  echo '' > "$file_lyrics"

fi

cat "$file_lyrics"
