#!/usr/bin/env sh
#
# DESCRIPTION:
#   Send to EWW a new lyrics part based on the index of EWW.
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

lyrics_max_lines=30
lyrics_max_columns=50

# C. Get lyrics with Iris and lyrics management to not download again the same lyrics.
lyrics="$(lyrics_song_mpd | sed -re "s/.{$lyrics_max_columns}[^\n]/&\n/g" | sed 's/^ \+//g')"

## D. If it exists.
if [ "$lyrics" ]; then

  index=$(eww get mpd_lyrics_index)
  lyrics_lines=$(echo "$lyrics" | wc -l)
  start=$(( $index * $lyrics_max_lines))
  end=$(($start + $lyrics_max_lines))

  # . Do not print a repeated line.
  #[ $index -gt 0 ] && start=$(($start - 1))

  # I. Set for the first line in case the start is bigger.
  [ $start = 0 ] && start=1

  # . To go back if the index goes beyond the text.
  [ $start -gt $lyrics_lines ] && eww update mpd_lyrics_index=0 && exec "$(which mpd_eww_lyrics)"

  # . Set lyrics only to the max range.
  [ $end -gt $lyrics_lines ] && end=$lyrics_lines

  # . Set lyrics to the chosen range of index.
  lyrics="$( echo "$lyrics" | sed -n "${start},${end}p;${end}q")"

  # . Center relatively the text.
  lyrics="$(center_text_relative "$lyrics")"

  # . Update the lyrics of EWW.
  eww update mpd_lyrics="$lyrics"

  if [ "$(eww get menu_is_open)" = 'true' ]; then

    eww close mpd-lyrics
    eww open mpd-lyrics
  
  fi

else

  eww close mpd-lyrics

fi

