#!/usr/bin/env sh
#
# Get colour from anywhere in screen and return its HEX code
#
# Dependencies
#   colorpicker : https://github.com/Jack12816/colorpicker
#   xclip
#   notification-send
#   imagemagick
#
# BeyondMagic 🄯 2021


stdbuf -i0 -o0 -e0 colorpicker --short --one-shot | while IFS=$'\n' read -r id_colour; do

  id_colour=$(printf "$id_colour" | tr -d '\n' )

  printf "$id_colour" | xclip -sel c &
  convert -size 50x50 xc:"$id_colour" /tmp/colour.png
  notify-send.sh -i "/tmp/colour.png" "'$id_colour'" "Was copied to your clipboard."

  exit

done
