#!/usr/bin/env sh
#
# DESCRIPTION:
#   Simple script to notify the volume settings of both sides
#   left and right
#
# DEPENDENCIES:
#   libnotify ; notify-send
#   libpulse ; pactl
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

[ "$1" = "increase" ] \
  && {
  pactl -- set-sink-volume @DEFAULT_SINK@ +2% &
} || {
  pactl -- set-sink-volume @DEFAULT_SINK@ -2% &
}

#"$SCRIPTS_FOLDER"/bars/module/top/_sound run > /tmp/top.fifo
