#!/usr/bin/env sh
#
# DESCRIPTION: 
#   Load random quote of a file.
#
# NOTE:
# -------quotes.json--------
#
#  [
#    "Your Majesty, we Catholic clergy have done our best to destroy the Church for the last eighteen hundred years. We have not succeeded, and neither will you.",
#    "Massimo Faggioli"
#  ],
#  [
#    "Daddy listen, Mommy please. There must be a better way to raise me, I yell until my ears can't hear me - into a silence that kills me.",
#    "Little People",
#    "The Procussions"
#  ]
#]
# ---------------------------
#
# DEPENDENCIES:
#   jq
#   shuf
#
# MAINTAINER: (s)
#   BeyondMagic : 2021- : <koetemagie@gmail.com>

quotes_path="$HOME/Library/quotes.json"

length_file=$(grep -c '  \[' "$quotes_path") #$(jq length "$quotes_path")
random_numb=$(shuf -i 0-$((length_file - 1)) -n 1)
quote_chose=$(cat "$quotes_path" | xq -r ".[$random_numb]" | tr '\r\n' ' ')

first_line=$(echo "$quote_chose" | xq -r ".[0]")
secon_line=$(echo "$quote_chose" | xq -r ".[1]")
third_line=$(echo "$quote_chose" | xq -r ".[2]")

echo "$first_line"
[ "$secon_line" != 'null' ] && echo "$secon_line"
[ "$third_line" != 'null' ] && echo "$third_line"

:
