#!/usr/bin/env sh
#
# DESCRIPTION:
#   This takes a screenshot using Imagemagick and puts unclutter back to its state.
#
# DEPENDENCIES:
#   xclip
#   notify-send.sh
#   imagemagick
#   slop
#   unclutter (optional)
#
# MAINTAINER: (s)
#   BeyondMagic : 2021- : <koetemagie@gmail.com>

scrot \
  -a $(slop -f '%x,%y,%w,%h') \
  -q 100 \
  -f '/tmp/last_shot.png' \
  -o

cat /tmp/last_shot.png | xclip -selection clipboard -target image/png

notify-send.sh -i "/tmp/last_shot.png" "Partial screenshot was copied to clipboard." &
