#!/usr/bin/env sh
#
# DESCRIPTION:
#   This takes a screenshot using Imagemagick and puts unclutter back to its state.
#
# DEPENDENCIES:
#   xclip
#   notify-send.sh
#   imagemagick
#   slop
#   unclutter (optional)
#
# MAINTAINER: (s)
#   BeyondMagic : 2021- : <koetemagie@gmail.com>

scrot \
  -a $(slop -f '%x,%y,%w,%h') \
  -f '/tmp/last_shot.jpg' \
  -o

cat /tmp/last_shot.jpg | xclip -selection clipboard -target image/png

size="$(identify -format '%wx%h' /tmp/last_shot.jpg)"

notify-send.sh -i "/tmp/last_shot.jpg" "Partial screenshot was copied to clipboard.\n$size" &
