#!/usr/bin/env sh
#
# DESCRIPTION:
#		Small menu to 
#
# BeyondMagic  GPL3 LICENSE  2021

option=$(echo "Power: Turn off." \
  "\nRestart: Quick restart." \
  "\nSleep: I'm an ice bear in the summer." \
  "\n-------------------------------------" \
  "\ndwm: Restart dwm instance." \
	| 91menu -g 0x0+1195+40 \
	| sed -r 's/:.+//')

case $option in

	Power)

		doas halt

	;;

	Restart)

		doas -- shutdown -r now

	;;

	Sleep)

		doas -- zzz	

	;;

  dwm)

		pkill -1 dwm

	;;


esac
