#!/usr/bin/env sh
#
# Load random quote of a file like this and put in slock
#
# -------quotes.json--------
#[
#  [
#    "Your Majesty, we Catholic clergy have done our best to destroy the Church for the last eighteen hundred years. We have not succeeded, and neither will you.",
#    "Massimo Faggioli"
#  ],
#  [
#    "Daddy listen, Mommy please. There must be a better way to raise me, I yell until my ears can't hear me - into a silence that kills me.",
#    "Little People",
#    "The Procussions"
#  ]
#]
# ---------------------------
#
# Dependencies
#   jq
#   shuf
#   slock
#     slock-message-xft
#
# BeyondMagic 🄯 2021

unset use

quotes_path="$HOME/git/startpage/data/quotes.json"

length_file=$(jq length "$quotes_path")
random_numb=$(shuf -i 0-$((length_file - 1)) -n 1)
quote_chose=$(jq -r ".[$random_numb]" "$quotes_path")

first_line=$(echo "$quote_chose" | tr '\r\n' ' ' | jq -r ".[0]")
secon_line=$(echo "$quote_chose" | tr '\r\n' ' ' | jq -r ".[1]")
third_line=$(echo "$quote_chose" | tr '\r\n' ' ' | jq -r ".[2]")

#sleep infinity

use="$first_line"

# Function
#   Center input text based on the terminal's size
center() {

  cols=100
  string="$@"

  [ "$string" = "null" ] || printf "%*s\n" $(((${#string}+$cols)/2)) "$string"

}




[ "$secon_line" = "null" ] || use="$use\n$(center "$secon_line")"
[ "$third_line" = "null" ] || use="$use\n$(center "$third_line")"

# mpc pause &

slock -m "$(printf "$use")"
