#!/usr/bin/env sh
#
# DESCRIPTION: 
#   Load random quote of a file.
#
# -------quotes.json--------
#
#  [
#    "Your Majesty, we Catholic clergy have done our best to destroy the Church for the last eighteen hundred years. We have not succeeded, and neither will you.",
#    "Massimo Faggioli"
#  ],
#  [
#    "Daddy listen, Mommy please. There must be a better way to raise me, I yell until my ears can't hear me - into a silence that kills me.",
#    "Little People",
#    "The Procussions"
#  ]
#]
# ---------------------------
#
# DEPENDENCIES:
#   jq
#   shuf
#
# BeyondMagic © 2021

quotes_path="$HOME/git/startpage/data/quotes.json"

length_file=$(jq length "$quotes_path")
random_numb=$(shuf -i 0-$((length_file - 1)) -n 1)
quote_chose=$(jq -r ".[$random_numb]" "$quotes_path")

first_line=$(echo "$quote_chose" | tr '\r\n' ' ' | jq -r ".[0]")
secon_line=$(echo "$quote_chose" | tr '\r\n' ' ' | jq -r ".[1]")
third_line=$(echo "$quote_chose" | tr '\r\n' ' ' | jq -r ".[2]")

# Function
#   Center input text based on the terminal's size
#center() {

#  cols=$(tput cols)
#  string="$@"

#  [ "$string" = "null" ] || printf "%*s\n" $(((${#string}+$cols)/2)) "$string"

#}

echo "$first_line"
[ "$secon_line" != 'null' ] && echo "$secon_line"
[ "$third_line" != 'null' ] && echo "$third_line"

:
