#!/usr/bin/env sh
#
# This takes a full screenshot using imagemagic and puts unclutter back to its state
# 
# BeyondMagic © 2021

killall unclutter
import -window root png:- | xclip -selection c -t image/png &
notify-send -i "/usr/share/icons/BeautyLine/actions/scalable/editimage.svg" "Full screenshot was copied to clipboard."
unclutter --timeout 1 & disown
exit
