#!/usr/bin/env sh
#
# DESCRIPTION:
#   This takes a screenshot using Imagemagick and puts unclutter back to its state.
#
# DEPENDENCIES:
#   xclip
#   notify-send.sh
#   imagemagick
#   unclutter (optional)
#
# MAINTAINER: (s)
#   BeyondMagic : 2021- : <koetemagie@gmail.com>

killall unclutter
import png:- | xclip -selection clipboard -t image/png
xclip -selection clipboard -t image/png -o > "/tmp/last_shot.png"
notify-send.sh -i "/tmp/last_shot.png" "Partial screenshot was copied to clipboard." &
nohup unclutter --timeout 1 >/dev/null 2>&1 &
exit
