#!/usr/bin/env sh
#
# This takes a screenshot using imagemagic and puts unclutter back to its state
#
# BeyondMagic © 2021

killall unclutter
import png:- | xclip -selection clipboard -t image/png
notify-send -i "/usr/share/icons/BeautyLine/actions/scalable/editimage.svg" "Partial screenshot was copied to clipboard." &
unclutter --timeout 1 & disown
exit
