#!/usr/bin/env sh
#
# DESCRIPTION:
#   Preview tag with nsxiv and close previous ones.
#
# DEPENDENCIES:
#   nsxiv
#
# NOTE:
#   github.com/beyondmagic/scripts/tree/master/bars
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

title_nsxiv="$(xgetres bars.preview.title)"

# Kill previous nsxiv runnings
[ "$title_nsxiv" ] && pkill -9 -f "$title_nsxiv"

# If there's previous preview scripts running to preview, just kill it.
[ "$1" = "close" ] && {
  
  pgrep -f "dash $SCRIPTS_FOLDER/bars/bottom/__preview_tag " | \
  while read -r id; do
    pkill -9 -P "$id"
    kill -9 "$id"
  done &
  pkill -9 -f "dash $SCRIPTS_FOLDER/bars/bottom/__preview_tag "

  exit 0

}

{

  sleep 1

  title_nsxiv="${title_nsxiv}:0"
  geome_nsxiv="$(xgetres bars.preview.geometry)"
  fname_nsxiv="/tmp/$1.jpg"

  nsxiv -bp -s F -T "$title_nsxiv" -g "$geome_nsxiv" "$fname_nsxiv"

}
