#!/usr/bin/env sh

# The famous "get a menu of emojis to copy" script.
#   Get user selection via dmenu from emoji file.
O="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

chosen=$(cut -d ';' -f1 $O/kuomojis | dmenu -i -l 10 | sed "s/ ###.*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
#   character. Otherwise, show a message that the emoji has been copied.
[ -n "$1" ] && {

  xdotool type "$chosen"

} || {

	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &

}
