#!/usr/bin/env sh
#
# The famous "get a menu of emojisto copy" script.
# Get user selection via dmenu from emoji file.
#
# Dependencies
#   dmenu
#   xdotool
#   libnotify ; notify-send
#   xclip
#
# Thanks LukeSmith for the base script
#
# TODO
#   add more descriptions for kaomojis
# 
# BeyondMagic © 2021

export PATH="$PATH:$HOME/.cargo/bin"

origin=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)
emojis="$origin/emojilist"
chosen=$(cat "$emojis" | dmenu -i -l 10 | sed "s/ ###.*//g")


# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
#   character. Otherwise, show a message that the emoji has been copied.
[ -n "$1" ] && {

  xdotool type "$chosen"

} || {

	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
  notify-send.sh "$chosen" "クリップボードにコピー."

}
