#!/usr/bin/env sh
#
# Description
#   Simple script to notify the volume settings of both sides
#   left and right
#
# Dependencies
#   libnotify ; notify-send
#   libpulse ; pactl
# 
# BeyondMagic © 2021

[ "$1" = "increase" ] \
  && {
  pactl -- set-sink-volume @DEFAULT_SINK@ +2% &
} || {
  pactl -- set-sink-volume @DEFAULT_SINK@ -2% &
}

$HOME/git/scripts/bars/top_bar/_sound run > $HOME/Base/lemon_bars/top.fifo
