#!/usr/bin/env sh
#
# DESCRIPTION:
#   Button to open a menu to do things.
# 
# DEPENDENCIES:
#   91menu
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

[ "$1" = "open_menu" ] && {

  option=$(echo "Power: Turn off." \
    "\nRestart: Quick restart." \
    "\nSleep: I'm an ice bear in the summer." \
    "\nLog-out: Leave current session." \
    "\n────────────────" \
    "\ndwm: Restart dwm instance." \
    | 91menu -g 0x0+1190+30 \
    | sed -r 's/:.+//')

  case $option in

    Power)

      doas halt

    ;;

    Restart)

      doas -- shutdown -r now

    ;;

    Sleep)

      doas -- zzz

    ;;

    dwm)

      pkill -1 dwm

    ;;

    Log-out)

#      nohup exec clearlovemii >/dev/null 2>&1 &
      exec clearlovemii

    ;;


  esac

}

_get_power() {

  icon=" "; affix="$(xgetres bars.separator4)"
  hover_block="%{A1:execute eww open powermenu:}"
  echo 'P' "$hover_block%{F$power_fg}%{B$power_bg}   $icon %{B-}%{A1}"
}

[ "$1" = "run" ] && {

  . $SCRIPTS_FOLDER/bars/config
  _get_power

}
