#!/usr/bin/env sh
#
# DESCRIPTION:
#   Display current volume percentage.
# 
# DEPENDENCIES:
#   pamixer
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

_get_audio() {

          symbol='─'
      multiplier=1
      min_volume=17
      max_volume=175
  current_volume=$(echo "$(pamixer --get-volume) - $min_volume" | bc)
  
  progress=$(echo "($current_volume*100/$max_volume*100)/100" | bc)
  
  [ $progress -gt 100 ] && progress=100
  
  # Format Icon
  [ $progress -ge 50 ]    && icon=""
  [ $progress -lt 50 ]    && icon=""
  [ $progress -le 0 ]     && icon=""
  
  done=$(echo "($progress*$multiplier)/10" | bc)
  left=$(echo "${multiplier}0-$done" | bc)

  done=$(printf "%${done}s" | sed -r "s/^/%{F$sound_bar_on}/g")
  left=$(printf "%${left}s" | sed -r "s/^/%{F$sound_bar_off}/g")

  increase_volume="%{A4:execute dash $HOME/git/scripts/pulseaudio/set_volume increase:}"
  decrease_volume="%{A5:execute dash $HOME/git/scripts/pulseaudio/set_volume:}"
       click_icon='%{A1:execute pavucontrol:}'
  
  echo 'T' "%{T4}%{F$sound_icon_on}$click_icon$icon%{A1}  $decrease_volume$increase_volume$(echo "%{T4}$done%{T3}%{O-4}%{T3}%{O-}$left" | sed "s/ /$symbol/g")%{A4}%{A5}"
 
}

[ "$1" = "run" ] && {

  . "$SCRIPTS_FOLDER"/bars/config
  _get_audio 


}
