#!/usr/bin/env sh
#
# Description
#   Load MPD info every 2 seconds
# 
# Dependencies:
#   mpd
#     mpc
#
# BeyondMagic © 2021


. $HOME/desktop/status_info


# This function is called to continue the loop throughout the song
#   It will be stopped/killed when MPD is stopped
#   Funny enough the same script being looped here
#   Is the one being used to stop this loop.
_loop_song() {

#  dance="$dance_r"
#  formated_icon=$(_icon_music "$icon_running" "$background_song_name" "$first_running_song_name" )
  
  
  while :; do
  
    mpc current --wait >/dev/null 2>&1 

    # notify song
    $HOME/github/scripts/mpd/song &

    _run_song

  done &

  while :; do

    _run_song
    sleep 2

  done

}

_loop_song
