#!/usr/bin/env sh
#
# Rewrote a few times
#
# BeyondMagic © 2021


             info=$(mpc)
             song=$(sed -n '1,1p' <<< "$info")
      song_length=${#song}
max_length_scroll="$3"

 start_st="%%{F$1}"
middle_st="%%{F$2}"
   end_st=""


[ ! -n $(pidof mpd) ] && {

  # If the return value is not 0, then echo nothing, since mpd is not running
  exit

} || {

    # mpd is running, so find out if it's playing or paused and echo the corresponding glyph
    grep -q "playing" <<< "$info" && {

      sleep 0

    } || {

      printf "paused";
      exit

    }

}



[ "$song_length" -ge "$max_length_scroll" ] && {

  # Read offset from file
  offset="$(($(cat /tmp/mpdoffset | head -n 1)))"

  # Add one
  offset="$(($offset + 1))"

  # Test if offset should be reset
  [ "$song" != "$(sed "2q;d" /tmp/mpdoffset)" ] && {

    rm /tmp/mpdoffset
    offset=0

  }

[ "$(($offset + $max_length_scroll - 1))" -ge "$song_length" ] && {

    rm /tmp/mpdoffset
    offset=0

  }

  # Write offset back to file
  echo -e "$offset\n$song" > /tmp/mpdoffset
  song="${song:$offset:$max_length_scroll}"

}




# Parse the info to get the progress in %
#   total=$(echo "$info" | sed -r "s/duration //;t;d")
#   progr=$(echo "$info" | sed -r "s/position //;t;d")
#   perc=$(awk -v n="$total" -v m="$progr" 'BEGIN{ print int(( m/n )*100) }')
       perc=$(echo "$info" | grep -oie "([[:digit:]]*%)" | tr '%' ' ' | tr '(' ' ' | tr ')' ' ')
song_length=${#song}
   perc_chr=$(awk -v n="$song_length" -v m="$perc" 'BEGIN{ print int( n*(m/100)) }')






song="$start_st${song:0:$perc_chr}$middle_st${song:$perc_chr:$song_length}$end_st"

printf "$song"
