#!/usr/bin/env sh
#
# Description
#   Just a script to give emails' number left to read :)
#   This one is using 4 emails
#
# Note
#   This is not yet fully optimized
#   It will get 4 of emails from an account from Google
#   You can edit this by setting your own variables
#   You have to enable the script and Google's settings
#   to allow such scripts to be loaded.
#
# BeyondMagic © 2021



background="#000000"


_messages() { while :; do

  . "$HOME/desktop/accounts"

            first_new_emails=$(curl -u $username_gmail_first:$password_gmail_first --silent "https://mail.google.com/mail/feed/atom" |  grep -oPm1 "(?<=<title>)[^<]+" | sed '1d')
  first_number_of_new_emails=$(echo "$first_new_emails" | wc -l)

            second_new_emails=$(curl -u $username_gmail_second:$password_gmail_second --silent "https://mail.google.com/mail/feed/atom" |  grep -oPm1 "(?<=<title>)[^<]+" | sed '1d')
  second_number_of_new_emails=$(echo "$second_new_emails" | wc -l)

            third_new_emails=$(curl -u $username_gmail_third:$password_gmail_third --silent "https://mail.google.com/mail/feed/atom" |  grep -oPm1 "(?<=<title>)[^<]+" | sed '1d')
  third_number_of_new_emails=$(echo "$third_new_emails" | wc -l)

            fourth_new_emails=$(curl -u $username_gmail_fourth:$password_gmail_fourth --silent "https://mail.google.com/mail/feed/atom" |  grep -oPm1 "(?<=<title>)[^<]+" | sed '1d')
  fourth_number_of_new_emails=$(echo "$fourth_new_emails" | wc -l)


  # if we have 0 new emails
  [ ! "$first_number_of_new_emails"  = "0" ] ||
  [ ! "$second_number_of_new_emails" = "0" ] ||
  [ ! "$third_number_of_new_emails"  = "0" ] ||
  [ ! "$fourth_number_of_new_emails" = "0" ] && {

    emoji="";
  colour_emoji="#ffffff"; background_emoji="#ffffff"; separator="%{F#555555}:"
number_of_new_emails="%{T1 F${colourof_gmail_first}}$first_number_of_new_emails${separator}%{F${colourof_gmail_second}}$second_number_of_new_emails${separator}%{F${colourof_gmail_third}}$third_number_of_new_emails${separator}%{F${colourof_gmail_fourth}}$fourth_number_of_new_emails"

  # if we have more than 1 email
  } || {

    emoji="﫯";
    colour_emoji="#ABABAB"; background_emoji="#1C0E2D"
    colour="#D4D4D4"
    number_of_new_emails=":("

  }


  echo 'G' "%{T3 B$background F$colour_emoji}　　$emoji %{T1 F#d4d4d4} $number_of_new_emails"

  sleep 120

done; }

_messages
