#!/usr/bin/env sh
#
# Description
#   Button to open a sidebar, it doesn't work yet
# 
# Note
#   It's just a label for now, I will create clickable button
#   When I find a minimalist siderbar for Linux
#   As for right now, there's no sidebar at all :(
# 
#   Maybe one day I'll create one
#   But that it'll take long time because I want to create it
#   in C++
#
# BeyondMagic  GPL3 LICENSE  2021

_get_power() {
  
  icon=" "; affix=""
  echo 'P' "%{A6:dash $HOME/git/scripts/bars/top_bar/power/__power:}%{F$power_bg}%{B-}$affix%{F$power_fg}%{B$power_bg} $icon  %{A6}"
}


