#!/usr/bin/env sh
#
# Description
#   Button to open a sidebar, it doesn't work yet
# 
# TODO
#   Label for power in Linux
#     shutdown -h now ; shutdown
#     shutdown -r now ; reboot
#     command to suspend
# 
# Note
#   It's just a label for now, I will create clickable button
#   When I find a minimalist siderbar for Linux
#   As for right now, there's no sidebar at all :(
# 
#   Maybe one day I'll create one
#   But that it'll take long time because I want to create it
#   in C++
#
# BeyondMagic © 2021

. $HOME/desktop/colours

icon=" "; affix=""

echo 'P' "%{A:doas halt:}%{F$bg_before_power B$power_bg}$affix%{F$power_fg} $icon  %{A}" &
