#!/usr/bin/env sh
#
# Description
#   Load MPD info every time MPD updates
# 
# Dependencies:
#   mpd
#     mpc
#
# BeyondMagic © 2021


# This source file will get two functions which are loaded every time you stop MPD
#   See (https://github.com/BeyondMagic/config/blob/main/_desktop/status_info)
#       (https://github.com/BeyondMagic/config/blob/main/_desktop/colours)
. $HOME/desktop/status_info


origin=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)

# This function is the main one and will get the information of MPD
#   It uses "mpc idleloop" method to gather MPD updates
#   This can be further simplified to only use MPD protocol,
#   however you need to edit the source code... which I'm
#   not with the will to do.
_music() {

  # Note: Neither "new_change" and "double_change" variables will be used
  mpc idleloop | while IFS=$'\n' read -r new_change && read -r double_change; do

    song=$($origin/mpd/__status "$first_running_song_name" "$second_running_song_name" "$limit_extra_length")

    # if paused
    #   If paused, then stop loop function
    [ "$song" = "paused" ] && {

      # stop song
      pkill -KILL -f "__loop_status"; pkill -KILL -f "mpc\ current\ \-\-wait"
      
      echo 'M' "%{F$second_running_song_name} $extra_icon_paused %{F-}" &

    # if running
    #   If running, then continues the loop function
    } || {

      # stop song
      pkill -KILL -f "__loop_status"

      # run thes script
      $origin/mpd/__loop_status &

    }

  done

  echo "- : •́ ◇ •̀ : -"; sleep 5
  exec "$origin/_song"

}


# Start
_music


