#!/usr/bin/env sh
#
# Description
#   Load a predetermined task from a "routine" file
#   Show task of the day based on a file.
#
# Note
#   Example of a file to load the tasks.
# -----file_name.txt------
#12:30-13:00 | Breakfast
#13:00-15:00 | Mathematics
# ------------------------
#
# BeyondMagic © 2021

. $HOME/desktop/colours

   file_task="$HOME/github/routine.txt"
svg_icon="/usr/share/icons/BeautyLine/apps/scalable/preferences-calendar-and-tasks.svg"
icon_routine=""


_get_tasks() {

  while :; do 

    while read line; do
  
        date_now=$(date +%H%M | sed -r "s_^0+__gm")
      start_hour=$(printf "$line" | sed -r "s_:__g" | cut -c 1-4)
        end_hour=$(printf "$line" | sed -r "s_:__g" | cut -c 6-9)
       task_line=$(printf "$line" | sed -r "s_:__g" | cut -c 13-)

      [ "$date_now" -ge "$start_hour" ] && [ "$date_now" -le "$end_hour" ] && {

        echo 'T' \
        "%{O-4 T3 F$task_fg_icon}$icon_routine %{T1 F$task_fg} $task_line%{B- F-}　　"

        [ "$date_now" = "$start_hour" ] && { 
          notify-send.sh -u critical -i \
          $svg_icon "$task_line"
        }

      }

    done < $file_task

    sleep 34

  done
}

_get_tasks
