#!/usr/bin/env sh
#
# Description
#   Load a predetermined task from a "routine" file
#   Show task of the day based on a file.
#
# Note
#   Example of a file to load the tasks.
# -----file_name.txt------
#12:30-13:00 | Breakfast
#13:00-15:00 | Mathematics
# ------------------------
#
# BeyondMagic © 2021

   file_task="$HOME/github/routine.txt"
icon_routine=""

       fg="#F8FFF8"
  fg_icon="#50D84F"

_get_tasks() {

  while :; do 

    while read line; do
  
      date_now=$(date +%H%M | sed -r "s_^0+__gm")
      start_hour=$(echo "$line" | sed -r "s_:__g" | cut -c 1-4) # | sed -r "s_^0+__g")
      end_hour=$(echo "$line" | sed -r "s_:__g" | cut -c 6-9) #| sed -r "s_^0+__g")
      task_line=$(echo "$line" | sed -r "s_:__g" | cut -c 13-)

      [ "$date_now" -ge "$start_hour" ] && [ "$date_now" -le "$end_hour" ] && {

        echo 'T' "%{O-4 T3 F$fg_icon}$icon_routine %{T1 F$fg} $task_line%{B- F-}　　"

        [ "$date_now" = "$start_hour" ] && { 
          notify-send.sh -u "critical" -i "/usr/share/icons/BeautyLine/apps/scalable/preferences-calendar-and-tasks.svg" "$task_line"
        }

      }

    done < $file_task

    sleep 29

  done
}

_get_tasks
