#!/usr/bin/env sh
#
# Load a predetermined task from a "routine" file
# Show task of the day based on a file.
# 
# Dependencies:
#   bash
#   tuxi
#
# BeyondMagic © 16/02/21

icon="  数学 "
affix=""

bg="#14181B";
fg="#F0F0F0";

error_fg="#FF5454"

 query_tuxi=$(echo "Math" | dmenu)
result_tuxi=$(TUXI_LANG="en_US" tuxi -trq "tuxi_math $query_tuxi" | sed "s/No Result!/%{F$error_fg}Nothing.../")




echo 'W' "%{T1 B$bg F$fg} $result_tuxi %{T3 F$bg B#FFFFFF}$affix" > $HOME/desktop/top.fifo
