#!/usr/bin/env sh
#
# Get temperature and precipitation
#
# Dependencies
#   tuxi
#   bash
#
# BeyondMagic © 2021

_temp() {

  utilites_fg="#555555"
  fg="#E4F2FF"
  bg="#14181B"

  tp_icon="  "
  pp_icon="  "
  hd_icon="  "

  while :; do

        tuxi_result=$(tuxi -trq "tuxi_weather weather now")
    formated_result=$(grep -hoE '[0-9]{2}' <<< "$tuxi_result" | sed \
      -e "2d;5d" \
      -e "1 s/$/%{F$utilites_fg}ºC /;1 s/^/%{F$fg B$bg T3}$tp_icon%{T1}/" \
      -e "3 s/$/%{F$utilites_fg}%% /;3 s/^/%{F$fg B$bg T3}$pp_icon%{T1}/" \
      -e "4 s/$/%{F$utilites_fg}%% /;4 s/^/%{F$fg B$bg T3}$hd_icon%{T1}/" \
      | tr '\n' ' ')
    
    echo 'W' "$formated_result"

    sleep 300

  done
}

_temp
