#!/usr/bin/env sh
#
# DESCRIPTION:
#   Colours for the modules.
#
# NOTE:
#   This is supposed to be used in 1.
#   1: https://github.com/BeyondMagic/scripts/tree/master/bars/modules
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

# Names for tags (notification) [./bottom/_layout]
name0="$(xgetres bars.name0)"
name1="$(xgetres bars.name1)"
name2="$(xgetres bars.name2)"
name3="$(xgetres bars.name3)"
name4="$(xgetres bars.name4)"
name5="$(xgetres bars.name5)"
name6="$(xgetres bars.name6)"
name7="$(xgetres bars.name7)"
name8="$(xgetres bars.name8)"
name9="$(xgetres bars.name9)"

# Preview [./bottom/_layout]
preview_geometry="$(xgetres bars.preview.geometry)"
preview_title="$(xgetres bars.preview.title)"

# Tags : Left [./bars/bottom/_layout]
bg_tags="$(xgetres bars.bottom.tags.bg)"
fg_selected="$(xgetres bars.bottom.tags.selected.fg)"
fg_unselect="$(xgetres bars.bottom.tags.unselected.fg)"
fg_selected_occupied="$(xgetres bars.bottom.tags.selected.occupied)"
fg_unselect_occupied="$(xgetres bars.bottom.tags.unselected.occupied)"
layout_fg="$(xgetres bars.bottom.layout.fg)"
layout_bg="$(xgetres bars.bottom.layout.bg)"
fg_unselect_all="$(xgetres bars.bottom.tags.unselected.all)"

# Titles : Center [./bottom/_title]
title_name_fg="$(xgetres bars.bottom.titles.title)"
title_icon_fg="$(xgetres bars.bottom.titles.icon)"

# Memory : Right [./bottom/_memory]
mem_colour="$(xgetres bars.bottom.memory.colour)"
mem_barra="$(xgetres bars.bottom.memory.bar)"

# Recording S : Right [./bottom/_recording] : Remote
recording_fg="$(xgetres bars.bottom.recording.fg)"

# Sound bar
sound_icon_on="$(xgetres bars.top.sound.icon.on)"
sound_icon_off="$(xgetres bars.top.sound.icon.off)"
sound_bar_on="$(xgetres bars.top.sound.bar.on)"
sound_bar_off="$(xgetres bars.top.sound.bar.off)"

# Clock : Left
clock_fg="$(xgetres bars.top.clock.fg)"
clock_bg="$(xgetres bars.top.clock.bg)"
clock_f_bg="$(xgetres bars.top.clock.fbg)"
clock_hg="$(xgetres bars.top.clock.ffg)"

# Sensors : Left
sensors_fg_affix="$(xgetres bars.top.sensors.affix.fg)"
sensors_bg_affix="$(xgetres bars.top.sensors.affix.bg)"
low_low_fg="$(xgetres bars.top.sensors.low.fg)"
low_low_bg="$(xgetres bars.top.sensors.low.bg)"
nor_low_fg="$(xgetres bars.top.sensors.normal.fg)"
nor_low_bg="$(xgetres bars.top.sensors.normal.bg)"
med_med_fg="$(xgetres bars.top.sensors.medium.fg)"
med_med_bg="$(xgetres bars.top.sensors.medium.bg)"
hig_med_fg="$(xgetres bars.top.sensors.high.fg)"
hig_med_bg="$(xgetres bars.top.sensors.high.bg)"

# Song : Center
background_before="$(xgetres bars.top.songs.before)"
background_icon="$(xgetres bars.top.songs.icon)"
background_song_name="$(xgetres bars.top.songs.song)"
first_running_song_name="$(xgetres bars.top.songs.song.first)"
second_running_song_name="$(xgetres bars.top.songs.song.second)"
background_icon_name="$(xgetres bars.top.songs.icon.name)"
neighbors_fg="$(xgetres bars.top.songs.neighbours)"
extra_icon_paused=$(xgetres bars.songs.icon.paused | sed -r 's/^"|"$//g')
limit_extra_length=$(xgetres bars.songs.extra.limit)
song_limit=$(xgetres bars.songs.title.limit)
bnotification_time=$(xgetres bars.songs.notification.time)

# Power But:wton : Right
power_fg="$(xgetres bars.top.power.fg)"
power_bg="$(xgetres bars.top.power.bg)"
