#!/usr/bin/env sh

origin=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

notify-send -i "/usr/share/icons/BeautyLine/apps/scalable/deskbar.svg" "Starting lemonbar in 15 seconds."

sleep 15

eval "$origin/bars" & disown
