#!/usr/bin/env sh
#
# DESCRIPTION:
#   Just get the swap and format it to lemonbar.
#
# DEPENDENCIES:
#   bc
#
# NOTE:
#   A swap file running in your system, or just disable it
#   by removing correctly where it contains `swap` names
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

_get_ram() {

  # Get total memory for once only
  memory_total=$(free | grep 'Mem:' | awk {'print $2'})

  while :; do

    # Destroy last msg variable before looping again
    unset msg mem_msg

    # Get current memory
    # Get only the used memory in 3rd line
    # Do math operation to know percentage
    mem_msg="$(echo "scale=4; $(free | grep 'Mem:' | \
      awk {'print $3'})/$memory_total * 100" | bc | sed -r 's/0+$//')"

    msg="$msg%{F$mem_barra}%{T3} %{F$mem_colour}%{T2}$mem_msg%{F$mem_barra}%"

    echo 'M' "$msg　　%{F-}%{B-} " &
    sleep 1

  done

}

[ "$1" = 'run' ] && {

  . "$SCRIPTS_FOLDER"/bars/config
  _get_ram

}
