#!/usr/bin/env sh
#
# DESCRIPTION:
#   Just get the swap and format it to lemonbar.
#
# DEPENDENCIES:
#   bc
#
# NOTE:
#   A swap file running in your system, or just disable it
#   by removing correctly where it contains `swap` names
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

[ "$1" = "open_menu" ] && {

  set is_suspend

  [ -f "/tmp/is_suspended" ] && {
    is_suspend="Resume: Will resume recording." 
  } || {
    is_suspend="Pause: Will pause recording."
  }
  
  option=$(echo "Stop: Will stop recording." \
    "\n$is_suspend" \
    | 91menu -g 0x0+1100+810 \
    | sed -r 's/:.+//')

  case $option in

    Pause)

      pacmd set-source-mute 0 1
      kill -STOP $(pgrep -f "ffmpeg -f alsa -ac 1 -i pulse -f x11grab -r 30 -s ")
      touch "/tmp/is_suspended"

    ;;

    Resume)

      pacmd set-source-mute 0 0
      kill -CONT $(pgrep -f "ffmpeg -f alsa -ac 1 -i pulse -f x11grab -r 30 -s ")
      rm "/tmp/is_suspended"

    ;;

    Stop)

      pacmd set-source-mute 0 0
      kill -CONT $(pgrep -f "ffmpeg -f alsa -ac 1 -i pulse -f x11grab -r 30 -s ")
      $SCRIPTS_FOLDER/record/record_size

    ;;

  esac

}

[ "$1" ] && {

  icon=""

  first_click="%{A1:execute dash $SCRIPTS_FOLDER/bars/module/bottom/_recording open_menu:}"
  middle_click="%{A2:execute dash $SCRIPTS_FOLDER/record/record_size:}"

  # $1 is being used here as the fifo of the bar
  echo 'R' "%{T3}$first_click$middle_click%{F$recording_fg}$icon%{A1}%{A2}%{T2}　" > "$1"

} || echo "/module/bottom/_recording: You have to call this script with the first argument being the fifo of the bar."
