#!/usr/bin/env sh
#
# DESCRIPTION:
#   Get the title of the active windows
#   You can set an icon for specific programs that you
#   Often use :)
#
# NOTE:
#   This formats for certain windows invidivually.
#   For example, for simple terminal (st), it
#   will display a certain icon.
#   You can change that by just creating a new 
#   condition in 'format_active_window'
#
# DEPENDENCIES:
#   xorg
#   dwm
#     dwm-msg
#   recode
#
# MAINTAINER: (s)
#   GPL3 🄯 BeyondMagic <koetemagie/gmail.com> 2021-

# Format a Process name based on ID
#   Note: it's ID, not PID
format_active_window() {

  icon=""
  process_id="$1"

  total=$(xprop -id "$process_id" | grep "_NET_WM_NAME" | sed -re 's/(_NET_WM_NAME\(UTF8_STRING\) = ")|"$//g' -e "")
  name=$(cat /proc/$(xdotool getwindowpid "$process_id")/comm)
  

  # st
  case "$name" in
  st)
    icon=""
    title_program=$(echo "$total" | sed -r 's/ .*//')
    total=$(echo "$total" | sed -r 's/\w* //')
    
    case "$title_program" in
      v) icon="";;
      mpd) 
        icon=""
        total=$(echo "$total" | sed -r "s/» *//g");;
      n) icon="";;
    esac

    ;;

  # Firefox-Developer-Edition
  GeckoMain)

    icon=""
    total=$(echo "$total" | sed -re 's/\\"/"/g' -e 's/(\[Sidebery\] )|( — Firefox.*)|( — Mozilla Firefox)//g' | recode html..ISO-8859-1)
    ;;

  # gcolor2
  gcolor2)
    
    icon=""
    ;;

  # nsxiv
  nsxiv)
    
    icon=""
    
    # Just ignore it's existence
    [ "$total" = "preview_dwm" ] && unset icon name total
    
    ;;

  # gimp
  gimp)
    
    icon=""
    ;;

  # mpv
  mpv)
    
    icon=""
    total=$(printf "$total" | sed 's/ - mpv$//')
    ;;

  # qbittorrent
  qbittorrent)
    
    icon=""
    ;;

  visualboyadvanc)
    
    icon=""
    ;;

  zathura)
    
    icon=""
    ;;

  telegram-deskto)
    
    icon=""
    ;;
  
  esac

  [ "$name" ] && {
  
      # Reduce length if it's bigger than 40 characters
    [ "${#total}" -gt "60" ] && total="$(echo "$total" | cut -c -60)..."
      # If there's no icon, then just prints out the name
    [ ! -n "$icon" ] && icon="$name" || icon="%{T3}$icon"
    
    echo 'T' "%{F$title_icon_fg}  $icon %{T2}%{F$title_name_fg}$total  %{T1}%{F-}"

  }

}

_get_active_window() {

  echo 'T' 'Hello there!'

  dwm-msg --ignore-reply subscribe focused_title_change_event client_focus_change_event |
    grep --line-buffered -oP '((?<=new_win_id": ).*)|((?<=client_window_id": )\d*)' |
    while IFS=$'\n' read -r winid; do
      [ $winid = "null" ] && {

        echo 'T'

      } || {

        format_active_window "$winid"

      }
    done

  echo "DWM died, resetting connection in 3 seconds"; sleep 3

  exec "$SCRIPTS_FOLDER/bars/module/bottom/_title" 'run'

}

[ "$1" = "run" ] && {

  . $SCRIPTS_FOLDER/bars/config
  _get_active_window

}
