#!/usr/bin/env sh
#
# Description
#   Load MPD info every time MPD updates
# 
# Dependencies:
#		91menu
#
# BeyondMagic  GPL3 LICENSE  2021

option=$(echo \
	"st: Open Simple Terminal." \
	"\nst-float: Open Simple Terminal in floating mode." \
	"\ndwm: Quick restart of dwm." \
	"\nfox: Open browser." \
	"\ntelegram: Open Telegram Desktop." \
	"\nrandom wallpaper: Random wallpaper." \
	"\nprevious wallpaper: Select previous wallpaper." \
	"\ndelete wallpaper: Delete current wallpaper." \
	| 91menu | sed -r 's/:.+//')

case "$option" in

	st)

		nohup st >/dev/null 2>&1 &

	;;

	st-float)

		nohup $HOME/git/scripts/terminal/st >/dev/null 2>&1 &

	;;

	dwm)

		pkill -1 dwm

	;;

	fox)

		xdo activate -N Nightly	|| nohup firefox-nightly >/dev/null 2>&1 &

	;;

	telegram)

		xdo activate -N telegram-desktop || nohup telegram-desktop >/dev/null 2>&1 &

	;;

	'random wallpaper')

		zsh -c '. ~/Base/aliasesrc; random_wallpaper'

	;;

	'previous wallpaper')	

		zsh -c '. ~/Base/aliasesrc; previous_wallpaper'

	;;

	'delete wallpaper')	

		zsh -c '. ~/Base/aliasesrc; delete_wallpaper'

	;;

esac
