#!/usr/bin/env sh
#
# DESCRIPTION:
#   Simple recording tool with ffmpeg.
#
# DEPENDENCIES:
#   ffmpeg
#   notify-send.sh
#   pkill (coreutils)
#
# MAINTAINER: (s)
#   BeyondMagic : 2021- : <koetemagie@gmail.com>

IS_RECORDING="/tmp/is_recording"
FIFO_BAR="/tmp/bottom.fifo"


[ -f "$IS_RECORDING" ] && {

  # Send signal to ffmpeg recorder
  pkill -INT -f "ffmpeg -f alsa -ac 1 -i pulse -f x11grab -r 30 -s "

  exit

}

SLOP_ARGS="$(slop -f "%w %h %x %y" | tr ' ' '\n')"

[ "$(echo "$SLOP_ARGS" | wc -l)" = 4 ] || exit 0

SIZE="$(echo "$SLOP_ARGS" | sed '1q;d')x$(echo "$SLOP_ARGS" | sed '2q;d')"
POSITION="$(echo "$SLOP_ARGS" | sed '3q;d'),$(echo "$SLOP_ARGS" | sed '4q;d')"
FRAME_RATE="30"
PATH_RECORDINGS="$HOME/.cache/ffmpeg"
FORMAT_FILE="mkv"
NAME_FILE="$PATH_RECORDINGS/record_$(date +'%a_%b_%d_%H:%M:%S').$FORMAT_FILE"
ICON_CAMERA="$HOME/Base/icons/camera.png"



mkdir -p "$PATH_RECORDINGS"




[ -f "$IS_RECORDING" ] || {

  # Create a file to verify if there is recording when this script is executed again
  touch "$IS_RECORDING"

  # Send a sign of recording to lemonbar so that you know it is being recorded.
  "$SCRIPTS_FOLDER/bars/module/bottom/_recording" "$FIFO_BAR"

  # Start recording
  ffmpeg -f alsa -ac 1 -i pulse \
         -f x11grab -r "$FRAME_RATE" -s "$SIZE" -i :0.0+"$POSITION" \
         -acodec pcm_s16le \
         -vcodec libx264 -preset ultrafast -crf 0 \
         -threads 0 \
         "$NAME_FILE"

  # Send a sign of recording to lemonbar so that you know it is not
  # being recorded anymore.
  echo 'R' '' > "$FIFO_BAR"

  # Remove the file since it stopped recording and there's no need to reverify it
  rm -rf "$IS_RECORDING"
  
  open_gtk="$(dunstify -i "$ICON_CAMERA" "Full recording was saved to '~/.cache/ffmpeg'." \
    -A "default,nothing")"
  
  [ "$open_gtk" = "default" ] && {
    nohup gtk-launch "$(xdg-mime query default inode/directory)" $NAME_FILE >/dev/null 2>&1 &
  }

}
