#!/usr/bin/env sh
#
# DESCRIPTION:
#   Simple recording tool with ffmpeg.
#
# DEPENDENCIES:
#   ffmpeg
#   notify-send.sh
#   pkill (coreutils)
#
# MAINTAINER: (s)
#   BeyondMagic 🄯 2021-



SIZE_MONITOR="1440x900"
FRAME_RATE="30"

PATH_RECORDINGS="$HOME/.cache/ffmpeg"
FORMAT_FILE="mkv"
NAME_FILE="$PATH_RECORDINGS/record_fullscreen_$(date +'%a_%b_%d_%H:%M:%S').$FORMAT_FILE"

FIFO_BAR="/tmp/bottom.fifo"
IS_RECORDING="/tmp/is_recording"
ICON_CAMERA="$HOME/Base/icons/camera.png"

mkdir -p "$PATH_RECORDINGS"



# Send a sign of recording to lemonbar so that you know it is being recorded.
# echo 'R' 'IS RECORDING!!!' > "$FIFO_BAR"

[ -f "$IS_RECORDING" ] || {

  # Create a file to verify if there is recording when this script is executed again
  touch "$IS_RECORDING"

  # Send a sign of recording to lemonbar so that you know it is being recorded.
  "$SCRIPTS_FOLDER/bars/module/bottom/_recording" "$FIFO_BAR"

  # Start recording
  ffmpeg -f alsa -ac 1 -i pulse \
         -f x11grab -r "$FRAME_RATE" -s "$SIZE_MONITOR" -i :0.0 \
         -acodec pcm_s16le \
         -vcodec libx264 -preset ultrafast -crf 0 \
         -threads 0 \
         "$NAME_FILE"

  # Send a sign of recording to lemonbar so that you know it is not
  # being recorded anymore.
  echo 'R' '' > "$FIFO_BAR"

  # Remove the file since it stopped recording and there's no need to reverify it
  rm -rf "$IS_RECORDING"

  open_gtk="$(dunstify -i "$ICON_CAMERA" "Full recording was saved to '~/.cache/ffmpeg'." \
    -A "default,nothing")"
  
  [ "$open_gtk" = "default" ] && {
    nohup gtk-launch "$(xdg-mime query default inode/directory)" $NAME_FILE >/dev/null 2>&1 &
  }

} && {

  # Send signal to ffmpeg recorder
  pkill -INT -f "ffmpeg -f alsa -ac 1 -i pulse -f x11grab -r 30 -s "

  exit

}
