#!/usr/bin/env sh

[ "$1" = "increase" ] && pactl -- set-sink-volume @DEFAULT_SINK@ +2% || pactl -- set-sink-volume @DEFAULT_SINK@ -2% 

$HOME/github/scripts/bars/top_bar/_volume > $HOME/desktop/top.fifo

notify-send $(pactl list sinks | grep "ボリューム" | head -n 1 | sed -r -e "s/\tボリューム: front-left: [0-9]* \/ +//" -e "s/ \/( | -)[0-9]*\.[0-9]* dB, *front-right: [0-9]*.{2} */ /" -e "s/ \/( | -)[0-9]*\.[0-9]* dB//" | tr -d '\n' | tr ' ' '-')
