#!/usr/bin/env sh
#
# DESCRIPTION:
#   Get tags of dwm.
#
# DEPENDENCIES:
#   dwm
#   dwm-msg
#
# TODO:
#   Clickable tags.
#
# github.com/beyondmagic/scripts/tree/master/bars

icon_selected=" $(xgetres bars.tags.selected)"
icon_selected_occupied=" $(xgetres bars.tags.selected.occupied)"
icon_unselect=" $(xgetres bars.tags.unselect)"
icon_unselect_occupied=" $(xgetres bars.tags.unselect.occupied)"

affix="$(xgetres bars.separator1)"
rv_affix="$(xgetres bars.separator2)"

_get_tags() {

  # A local function to shout out a tag name based
  # on their IDs, you can change it to whatever
  # you want to
  get_name_of_tag() {

    case $1 in
      1)   name="$name0" ;;
      2)   name="$name1" ;;
      4)   name="$name2" ;;
      8)   name="$name3" ;;
      16)  name="$name4" ;;
      32)  name="$name5" ;;
      64)  name="$name6" ;;
      128) name="$name7" ;;
      256) name="$name8" ;;
      511) name="$name9" ;;
    esac

    # Change to your notify program, I recommend a lot this though
    # Pretty lightweight!
    echo "$name" > "$XNOTIFY_FIFO"

    # Save image to preview later with nsxiv
    {
      sleep 0.125
      scrot -q 50 -o /tmp/"$name".jpg
    } &
    
  }


  dwm-msg --ignore-reply subscribe tag_change_event |
  jq --unbuffered '.tag_change_event.new_state | .selected, .occupied' |
  while IFS=$'\n' read -r selected && read -r occupied; do 


    # Loop through all the 9 tags
    # It starts from 0
    out=""; tag=0; while [ $tag -le 8 ]; do


      # Does this really needs any explanation?
      bit=$((1 << $tag))

      # Selected and with programs
      if [ $(($selected & $bit)) -ne 0 ] && [ $(($occupied & $bit)) -ne 0 ]; then
        # Pretty output (with external variables)
        out="${out}%{F$fg_selected_occupied} $icon_selected_occupied"
        # Simple output
        # out="${out} X"

      # Selected without programs
      elif [ $(($selected & $bit)) -ne 0 ]; then
        # Pretty output (with external variables)
        out="${out}%{F$fg_selected} $icon_selected"
        # Simple output
        # out="${out} o"

      # Not selected with programs
      elif [ $(($occupied & $bit)) -ne 0 ]; then
        # Pretty output (with external variables)
        out="${out}%{F$fg_unselect} $icon_unselect"
        # Simple output
        # out="${out} +"

      # Nothing at all
      else
        # Pretty output (with external variables)
        out="${out}%{F$fg_unselect_all} $icon_unselect_occupied"
        # Simple output
        # out="${out} -"

      fi


    tag=$((tag+1)); done

    #kill $!
    
    # If the last select is the same as the one right now, then does not print
    # out anything
    [ "$last_selected" = "$selected" ] || {

      # Give a quick notification
      get_name_of_tag "$selected" &
      
    }

    # Define last selected to be used on the next tag change
    last_selected="$selected"


    # Pretty output (with external variables)
    echo 'W' "%{T3 B$bg_tags}$out  %{F$bg_tags B-}$rv_affix"
    # Simple output
    # echo 'W' "$out"

  done
  
}



# Layout of the tag, the symbol that appears can be changed
_get_layout() {

  # Loop through every change and wait for the next one :)
  # If it breaks, see the last comments!
  dwm-msg --ignore-reply subscribe layout_change_event | \
    grep --line-buffered -oP '(?<=new_symbol": ").*' | \
    sed -u 's/",$//' | \
    while IFS=$'\n' read -r tagid; do

      # Beautify with colours, I recommend using the later one if
      # you don't have idea where the rest of the colours/variables come
      echo 'L' "%{O-5 B$layout_bg F$layout_fg T1}  " \
               "$tagid %{F$bg_tags B$layout_bg}$affix%{B$bg_tags F-}"

      # Simple output
      # echo 'L' "$tagid"

    done

  # Just a little warning that well, something died!
  # This is necessary because the loop isn't supposed to break,
  # however, it does when dwm is killed or restarted.
  # So this resets it!
  echo "DWM died, resetting connection in 5 seconds"; sleep 3

  # Execute itself and/by killing this
  exec "$SCRIPTS_FOLDER/bars/bottom/_layout" 'run'

}

[ "$1" = "run" ] && {

  . "$SCRIPTS_FOLDER"/bars/config
  _get_layout &
  _get_tags

}
