#!/usr/bin/env sh
#
# DESCRIPTION:
#   Button to open a sidebar, it doesn't work yet
# 
# DEPENDENCIES: 
#   91menu
#
# https://github.com/BeyondMagic/scripts/tree/master/bars

[ "$1" = "open_menu" ] && {

  option=$(echo "Power: Turn off." \
    "\nRestart: Quick restart." \
    "\nSleep: I'm an ice bear in the summer." \
    "\n-------------------------------------" \
    "\ndwm: Restart dwm instance." \
    | 91menu -g 0x0+1195+40 \
    | sed -r 's/:.+//')

  case $option in

    Power)

      doas halt

    ;;

    Restart)

      doas -- shutdown -r now

    ;;

    Sleep)

      doas -- zzz	

    ;;

    dwm)

      pkill -1 dwm

    ;;


  esac

}

_get_power() {
  
  icon=" "; affix="$(xgetres bars.separator4)"
  hover_block="%{A1:execute dash $SCRIPTS_FOLDER/bars/top/_power open_menu:}"
  
  echo 'P' "$hover_block%{F$power_bg}%{B-}$affix%{F$power_fg}%{B$power_bg} $icon  %{A1}"
}

[ "$1" = "run" ] && {

  . $SCRIPTS_FOLDER/bars/config
  _get_power

}
