#!/usr/bin/env sh
#
# Description
#   Get tags of dynamic window manager
#
# Dependencies
#   dwm
#   dwm-msg
#
# BeyondMagic © 2021

# possible bashism in _layout line 29 ($'...' should be "$(printf '...')"):
#   while IFS=$'\n' read -r selected && read -r occupied; do
# error: _layout:  Unterminated heredoc found, EOF reached. Wanted: <$tag))>, opened in line 35


         icon_selected=" "
icon_selected_occupied=" "
         icon_unselect=" "
icon_unselect_occupied=" "

affix=""

. $HOME/desktop/colours

origin=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)

_get_tags() {

  dwm-msg --ignore-reply subscribe tag_change_event |
  jq --unbuffered '.tag_change_event.new_state | .selected, .occupied' |
  while IFS=$'\n' read -r selected && read -r occupied; do 

    out=""

    tag=0; while [ $tag -le 8 ]; do

      bit=$((1 << $tag))

      if [ $(($selected & $bit)) -ne 0 ] && [ $(($occupied & $bit)) -ne 0 ]; then
        out="${out}%{F$fg_selected_occupied} $icon_selected_occupied"

      # selected
      elif [ $(($selected & $bit)) -ne 0 ]; then
        out="${out}%{F$fg_selected} $icon_selected"

      # have windows on it
      elif [ $(($occupied & $bit)) -ne 0 ]; then
        out="${out}%{F$fg_unselect} $icon_unselect"

      # nothing
      else
        out="${out}%{F$fg_unselect} $icon_unselect_occupied"
      fi

    tag=$((tag+1)); done

    echo 'W' "%{T3 B$bg_tags}$out  %{F- B-}"
    
  done

}

_get_layout() {

  dwm-msg --ignore-reply subscribe layout_change_event | grep --line-buffered -oP '(?<=new_symbol": ").*' | sed -u 's/",$//' |
  while IFS=$'\n' read -r tagid; do

    echo 'L' "%{O-5 B$layout_bg F$layout_fg T1}   $tagid %{F$bg_tags B$layout_bg}$affix%{B$bg_tags F-}"

  done

  echo "DWM died, resetting connection in 5 seconds"; sleep 5

  exec "$origin/_layout"

}

_get_tags & _get_layout
