#!/usr/bin/env sh
#
# Description
#   Just get the swap and format it to lemonbar
#
# Dependencies
#   
# Note
#   A swap file running in your system, or just disable it
#   by removing correctly where it contains `swap` names
#
# BeyondMagic © 2021


. $HOME/desktop/colours "b"


_get_ram() {

  while :; do

    msg=""

    memory=$(free -h | grep 'Mem:')
    memory_total=$(echo $memory | awk {'print $2'} | tr -d ' ')
    memory_used=$(echo $memory | awk {'print $3'} | tr -d ' ')
    mem_msg="$memory_used%{F$mem_barra}/%{F-}$memory_total"

    swap=$(free -h | grep 'Swap:')
    swap_total=$(echo $swap | awk {'print $2'} | tr -d ' ')
    swap_used=$(echo $swap | awk {'print $3'} | tr -d ' ')
    swap_msg="$swap_used%{F$swap_barra}/%{F$swap_colour}$swap_total"

    msg="$msg%{F$mem_barra T3} %{F$mem_colour T2}$mem_msg"
    msg="$msg%{F$swap_icon_colour T3}  %{F$swap_colour T2}$swap_msg"

    echo 'M' "$msg　　%{F- B-} "
    sleep 30

  done

}

_get_ram
