#!/usr/bin/env sh
#
# Description
#   Just get the swap and format it to lemonbar
#
# Dependencies
#   
# Note
#   A swap file running in your system, or just disable it
#   by removing correctly where it contains `swap` names
#
# BeyondMagic © 2021


. $HOME/desktop/colours "b"


_get_ram() {

  # Get total memory for once only
  memory_total=$(free | grep 'Mem:' | awk {'print $2'})

  while :; do

    # Destroy last msg variable before looping again
    unset msg

    # Get current memory
    # Get only the used memory in 3rd line
    # Do math operation to know percentage
    mem_msg="$(echo "scale=4; $(free | grep 'Mem:' | \
      awk {'print $3'})/$memory_total * 100" | bc | sed -r 's/0+$//')"

    msg="$msg%{F$mem_barra T3} %{F$mem_colour T2}$mem_msg%{F$mem_barra}%"

    echo 'M' "$msg　　%{F- B-} " &
    sleep 5

  done

}

_get_ram
